services:

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - volume_mariadb:/var/lib/mysql
    restart: on-failure
  
  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: on-failure
    ports:
      - "80:80"

volumes:
  volume_mariadb:
    driver: local
    driver_opts:
      type: none
      device: ./requirements/mariadb/data
      #allow to add an existent folder
      o: bind