services:

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - volume_mariadb:/var/lib/mysql
    restart: on-failure
    networks:
      - docker_network
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WP_DBNAME=${WP_DBNAME}
    
  
  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: on-failure
    ports:
      - "8080:80"
    networks:
      - docker_network
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WP_DBNAME=${WP_DBNAME}
    depends_on:
      - mariadb
    restart: on-failure
  
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    depends_on:
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    restart: on-failure
    

volumes:
  volume_mariadb:
    driver: local
    driver_opts:
      type: none
      device: ./requirements/mariadb/data
      #allow to add an existent folder
      o: bind

networks:
  docker_network: